export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';
export const CHANGE_PUBLICATION_NAME = 'CHANGE_PUBLICATION_NAME';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
